### PR TITLE
Feature/karma badge implementation

### PR DESCRIPTION
**Pull request by Cold-A-Muse**
## Proposed Changes
To make a property more personal, more information should be available in regard to the author of a pool
## Implementation
- Author of pool
- Karma badge of author
- Address of author which links to etherscan
- New set of icons (react-feather)

### CODE REVIEW

**Comment by k3nt0w** [comment]
Thank you for your Pull Request:tada:

There are a few areas that I would like you to fix to fit the current implementation. I am very sorry for the many changes to your implementation due to our lack of documentation of the development procedures:bow: If you have the time, our community would be very happy if you could fix the implementation as advised below!

### 1. Please use `useSWR` for fetch data.
We use SWR for API communication from within the react component. The source of the data is a new one, `https://api.devprtcl.com/v1/property/`, so we need to create a new devprtcl directory in the fixtures directory and implement the hooks there. Using SWR, I don't think your implementation of useFetch will be necessary.

FYI: [stakes.social/packages/web/src/fixtures/github at main · dev-protocol/stakes.social · GitHub](https://github.com/dev-protocol/stakes.social/tree/main/packages/web/src/fixtures/github)

### 2. Please use `@ant-design/icons` for Icon set

We use antd as a library for our design system.
This library also has a set of icons, and we want you to use this set of icons as well. 

FYI: https://github.com/dev-protocol/stakes.social/blob/5c16a32a3f9e5e0acf0aa6d0b4692fdc238e83be/packages/web/src/components/organisms/PoliciyList/index.tsx#L4 

### 3. Please do a strict type check

If the implementation contains `any type`, make sure that the type is properly inferred. Perhaps a change to the implementation using SWR as explained above would infer the correct type.

### 4. Please write the test codes

We mandate that snapshot tests and hooks tests must be implemented. We would like you to mimic the following reference material and add snapshot testing and hooks testing.

https://github.com/dev-protocol/stakes.social/blob/026d6cff398213cf9b58cea6c0787d19c1abac09/packages/web/src/fixtures/github/hooks.spec.ts#L10-L16

https://github.com/dev-protocol/stakes.social/blob/026d6cff398213cf9b58cea6c0787d19c1abac09/packages/web/src/fixtures/github/hooks.spec.ts#L10-L16

**Comment by Cold-A-Muse** [comment]
Hi @k3nt0w :smile: 
Thank you for your response! It is good to know you are following such guidelines :) 
I have taken care of point 1, 2, 3 and added hook testing for the new getPropertyInformation hook.
I am not sure sure how to do the snapshot chatting? Can you help me out with that one?

**Comment by Cold-A-Muse** [comment]
Nvm I got it :) snapshot test has been updated as well! Is the PR okay now?

**Comment by Cold-A-Muse** [comment]
Nice! Thank you both for commenting! Do I merge this PR myself or is someone else going to do this?

**Comment by k3nt0w** [comment]
@Cold-A-Muse 
Thanks! We'll merge this pr soon, so you don't warry about it:smile:

@aggre 
If you don't seem to have a problem with this PR, could you merge it :pray:?

**Comment by aggre** [comment]
@k3nt0w Yeah, I merge this!

**Pull request merged**
