### PR TITLE
docs: improved readme & created CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vinzvinci**
Screenshots of new README.md:

image

Demo of the readme here: https://github.com/vinzvinci/stakes.social

### CODE REVIEW

**Comment by vinzvinci** [comment]
Can you fix this issue @aggre?

This error already exists to other people:
- https://github.com/vercel/vercel/issues/3774
- https://github.com/vercel/vercel/blob/main/errors/now-next-routes-manifest.md

**Comment by aggre** [comment]
@vinzvinci The latest main branch has already solved the Vercel related problems. Could you merge the latest main branch into your branch?

**Comment by vinzvinci** [comment]
Updated.

**Comment by aggre** [comment]
LGTM!
LGTM

**Pull request merged**
