### PR TITLE
Improve stake and withdraw form

### LINKED ISSUE #877: Stake and Withdraw inputs should be hidden when not signed in
They do nothing when not signed in. If you think they should still be visible, they should at minimum be disabled.

Example: https://stakes.social/0x90168f9Ba07B95f629f8b77F789d46A549d6470F

### PR DESCRIPTION
**Pull request by hhatto**
## Proposed Changes
Fixes #877 

Before change:
before

After change:
_disable form_
after

_When the `Stake` or `Withdraw` button is pressed, it will output a message prompting the user to sign in._
signingin

### CODE REVIEW

**Comment by Cold-A-Muse** [comment]
I have edited the disabled property to the inputs when no account is available in useProvider(). A little more neat in my opinion. What do you think @hhatto ? If you are okay with it I will merge the code :+1:

**Comment by Cold-A-Muse** [comment]
Also, you want to be able to fill in "0" in the withdraw component because that indicates that people only want to withdraw their rewards

**Comment by hhatto** [comment]
> I have edited the disabled property to the inputs when no account is available in useProvider(). A little more neat in my opinion

LGTM 👍

**Comment by hhatto** [comment]
> Also, you want to be able to fill in "0" in the withdraw component because that indicates that people only want to withdraw their rewards

Fix 6b8e7c4

**Pull request merged**
