### PR TITLE
V3: Revisions round 2

### PR DESCRIPTION
**Pull request by hhatto**
## Proposed Changes
re-create PR for #717

Feedback in Air table by Scott.
This PR serves as a way to communicate with Scott in regard to the made changes based on his feedback.
Once it is approved by Scott, I will open it for review.

## Implementation

---

Edit by @aggre 
I put the preview link here because there is too much activity, and it's hard to find the Vercel preview link.
🔍 Inspect: https://vercel.com/devprtcl/stakes-social/mn05dcnz6
✅ Preview: https://stakes-social-git-cold-a-muse-feature-ui-revamp-with-fi-a427de.devprtcl.now.sh

### CODE REVIEW

**Comment by aggre** [comment]
@hhatto Thanks for your fix the conflicts! Should delete estimated annual rewards section.

image

**Comment by aggre** [comment]
I'm working on the fixing.

**Comment by hhatto** [comment]
@aggre 
> Should delete estimated annual rewards section.

So I can just remove the section itself? ( or only remove description? )

Do you want to keep the "Withdrawable reward amount" section as it is?

**Comment by aggre** [comment]
I deleted the estimate section. Users don't know how much withdrawable reward, so I added that amount to the stats section.

image

**Review by aggre — APPROVED** [review]
I fixed the stake/withdraw section, so I think already mergeable this PR!

**Pull request merged**
