### PR TITLE
Geyser v2

### PR DESCRIPTION
**Pull request by kazu80**

### CODE REVIEW

**Review by aggre — APPROVED** [review]
lgtm
anime

**Comment by aggre** [comment]
@kazu80 Deployment is failing https://vercel.com/devprtcl/stakes-social/EmW1ku5oSzzQA3Btr53qaEgkSwyg

Can you inspect this?

**Comment by kazu80** [comment]
> @kazu80 Deployment is failing https://vercel.com/devprtcl/stakes-social/EmW1ku5oSzzQA3Btr53qaEgkSwyg
> 
> Can you inspect this?
Thank you @aggre 
Yes. I fixed it

**Review by aggre — APPROVED** [review]

**Comment by aggre** [comment]
Nice! Let's merge this tomorrow when we started the Geyser v2

**Pull request merged**
