### PR TITLE
#446 create a landing page for creators

### PR DESCRIPTION
**Pull request by DomEscobar**
## Proposed Changes
#446
Find the Page on /about-creators

Try:
https://stakes-social-git-446-creators-how.devprtcl.vercel.app/about-creators

## Implementation
screencapture-localhost-3000-about-creators-2020-10-11-22_15_21

### CODE REVIEW

**Comment by aggre** [comment]
Great work! 

Static files, such as images, can be managed in this repository: https://github.com/dev-protocol/asset.stakes.social

However, I'll do a little bit of inspecting as well, as Next.js should also be able to host them.

**Comment by aggre** [comment]
@DomEscobar  When hosting Next.js in conjunction with "yarn workspaces" with Vercel, I noticed a configuration issue that prevented hosting static files. (I've ticketed this issue)

It's a little bit of work, but put the image file in `/public` in [dev-protocol/asset.stakes.social](https://github.com/dev-protocol/asset.stakes.social). They can be accessed over the Internet with paths like asset.stakes.social/foo/bar.jpg.

**Comment by DomEscobar** [comment]
This MR js read for review

**Comment by aggre** [comment]
@DomEscobar This looks perfect! 

I merge this!

**Pull request merged**
