### PR TITLE
merge `main` into `v3`

### PR DESCRIPTION
**Pull request by aggre**
## Proposed Changes

The liquidity mining page is ahead of the `main` branch, so I want to merge them into `v3`.

Some conflicts arose and I fixed them.

I hope @hhatto-san will review this PR, especially since it has a lot of conflicts with #657 .

### CODE REVIEW

**Comment by aggre** [comment]
@hhatto I mainly changed "src/fixtures/_pages/liquidity/geyser/hooks.ts."

The changes are to get the account address by "useGetAccountAddress" instead of taking "Web3" as an argument.

This streamlines the SWR cache.

https://github.com/dev-protocol/stakes.social/blob/e57d615a334648775353777d7f6b13ce074a1db1/packages/web/src/fixtures/_pages/liquidity/geyser/hooks.ts#L223-L266

https://github.com/dev-protocol/stakes.social/blob/e57d615a334648775353777d7f6b13ce074a1db1/packages/web/src/fixtures/_pages/liquidity/geyser/hooks.ts#L268-L279

**Comment by hhatto** [comment]
The current I/F of `useGetAccountAddress` is as follows and `web3` is not required.

```
export const useGetAccountAddress = (web3?: any) => {
```

However, you need to pass the `web3` to get the address, so I don't think this process works well.
You need to pass the `web3` as an argument to `useGetAccountAddress`.

The I/F in `useGetAccountAddress` that I changed in #657  may not be so good.
Instead of passing the web3 provider to `useGetAccountAddress`, it would be better to get the `web3` provider from the context(`WalletContext`) in `useGetAccountAddress` and use it.

I'm imagining the following change:
```diff
diff --git a/packages/web/src/fixtures/wallet/hooks.ts b/packages/web/src/fixtures/wallet/hooks.ts
index 69a459a..b86e1d2 100644
--- a/packages/web/src/fixtures/wallet/hooks.ts
+++ b/packages/web/src/fixtures/wallet/hooks.ts
@@ -23,7 +23,8 @@ export const useConnectWallet = () => {
   return { isConnected, connect, isConnecting: isConnecting }
 }

-export const useGetAccountAddress = (web3?: any) => {
+export const useGetAccountAddress = () => {
+  const { web3 } = useContext(WalletContext)
   const shouldFetch = web3 ? true : false
   const { data, error } = useSWR<UnwrapFunc<typeof getAccountAddress>, Error>(
     shouldFetch ? cachePath.getAccountAddress() : null,
```

May I make these changes? @aggre

**Comment by hhatto** [comment]
Specifically, these changes are as follows:
https://github.com/dev-protocol/stakes.social/compare/v3-merge-liquidity...v3-merge-liquidity-with-some-improve?expand=1


I have tested it and I have no problem getting this to work as is.

**Comment by aggre** [comment]
@hhatto Indeed! I changed the codes.

https://github.com/dev-protocol/stakes.social/blob/3c3a45f9183d00abf0cba57baa10a31ff66ab177/packages/web/src/fixtures/wallet/hooks.ts#L26-L34

**Review by hhatto — APPROVED** [review]
LGTM 👍

**Pull request merged**
