### PR TITLE
feat: updated the cancel flow to make better UX

### PR DESCRIPTION
**Pull request by k3nt0w**
## Proposed Changes

- The responsibilities and names of button card molecules have been changed
- Having different responsibilities ( `Cancel` and `Withdraw` ) on the same Button could cause confusion for the user, so I implemented it as a separate button.
  - The button toggles depending on the status.

スクリーンショット 2020-06-13 21 21 33

## Implementation

- Implemented Cancel Staking -> Withdraw Staking Flow

## Remaining tasks

- [ ] Operation check with wallet for production environment
- [ ] Block counting

### CODE REVIEW

**Comment by k3nt0w** [comment]
@aggre 
Could you check the operation on cancellation and withdraw :pray:?  I can't do Withdraw because I don't have the currency.

Also, the UI part is implemented differently from the specification of DropBox paper. If one button is capable of performing two processes, the user may be confused by the I implemented separate buttons to handle cancel and withdraw. Please let me know if you have any issues with this, as it differs from the UI in the documentation.

**Comment by k3nt0w** [comment]
@aggre 
I also have a question about the number of blocks.

Can this one be implemented by just displaying the value that can be obtained with `(Dev Kit).lockupStorage.getWithdrawalStatus`? Or do you need to do some calculations with the latest block count you can get from this API（https://web3js.readthedocs.io/en/v1.2.7/web3-eth-subscribe.html#subscribe-newblockheaders）?

Also, I'm not fully aware of the specs here, so let me implement the implementation on "number of blocks" in a separate PR :bow:

**Comment by aggre** [comment]
@k3nt0w Thank you for great implementation!

I could confirm that works on the mainnet! 🎉

Usually, we should have a testnet for debugging. It's hard to debug because we don't have that. I'm sorry.

There's a problem with the specs for switching between Cancel and Withdraw disable, so I'll commit afterward.

**Comment by aggre** [comment]
@k3nt0w I committed it → https://github.com/dev-protocol/stakes.social/commit/f0bc0011a8642dfeea179c8bf169d13caf26b91e

Summary:
- To enable Withdraw button, should depend only `getWithdrawStatus` (If not, become cannot Withdraw when reloading a page after Cancel)
- Correctly, it should call that( https://github.com/dev-protocol/stakes.social/commit/f0bc0011a8642dfeea179c8bf169d13caf26b91e#diff-0d97f294a666268bf9eaebc38cb20190R43 ) function on each block. To that needs block subscribing, but I also think it's a good idea to make it a separate PR.

**Pull request merged**
