### PR TITLE
Uniswap analytics

### PR DESCRIPTION
**Pull request by hhatto**
## Proposed Changes
add chart via Uniswap V2

* daily price
* daily volume
* daily liquidity

uniswap-analytics

## Implementation
* get data from [Uniswap V2 graphql API - Token Daily Aggregated](https://uniswap.org/docs/v2/API/queries/#token-daily-aggregated)
* chart rendering with [amCharts](https://www.amcharts.com/javascript-charts/)
* I haven't considered the design very much

### CODE REVIEW

**Comment by Cold-A-Muse** [comment]
Is this feature ready to be deployed @hhatto?

**Comment by hhatto** [comment]
As far as features are concerned the necessary implementation is finished 👌 
You can have them merged at design and release timing.

**Comment by Cold-A-Muse** [comment]
Okay thanks I will have a look once I have merged main into my branch :+1:

**Comment by aggre** [comment]
I think it's mergeable when passed the CI.

**Pull request merged**
