### PR TITLE
Creator page button profile

### LINKED ISSUE #812: Profile dashboard should have a link to view and edit public profile
https://stakes.social/profile should have these links.

It took me a while to realize I had to go to https://stakes.social/author/[ID] which has a "Edit" button.

### PR DESCRIPTION
**Pull request by Cold-A-Muse**
## Proposed Changes

Added view and edit profile buttons to portfolio page
Fixes #812

### CODE REVIEW

**Comment by Cold-A-Muse** [comment]
Apologies i have added the disable branch to this one by accident :flushed: . 
Please merge that one first before looking into this one :pray:

**Comment by aggre** [comment]
> Apologies i have added the disable branch to this one by accident 😳 .
> Please merge that one first before looking into this one 🙏

@Cold-A-Muse Sorry, which branch?

**Comment by Cold-A-Muse** [comment]
> > Apologies i have added the disable branch to this one by accident 😳 .
> > Please merge that one first before looking into this one 🙏
> 
> @Cold-A-Muse Sorry, which branch?

The branch i was mentioning has already been merged by @hhatto so this one can be merged as well now :)

**Comment by aggre** [comment]
Good!

**Pull request merged**
