### PR TITLE
V3 revisions part 4

### PR DESCRIPTION
**Pull request by Cold-A-Muse**
## Proposed Changes
Tons of changes
## TODO
Please see if you can do while i am asleep and otherwise I do it later myself
- [x] Error: The Serverless Function "__NEXT_PAGE_LAMBDA_0" is 50.6mb which exceeds the maximum size limit of 50mb.  (@aggre)
- [x] Display name as name of creator page using dev-for-apps hook api (e.g. /author/0x00000C64586fC178E566aBadfD1119c03849520e) (@hhatto)
- [ ] Page logic invitation -> tokenization -> authentication (@aggre )
- [x] Profile header of creator page (@aggre)
- [ ] Property icon per pool on creator page -> Is here a field for in strapi API? (@hhatto/ @aggre)
- [x] Add creator description in About section from strapi API (@hhatto)

### CODE REVIEW

**Comment by aggre** [comment]
@Cold-A-Muse Thank you for the PR. I will answer some.

---

>  Error: The Serverless Function "__NEXT_PAGE_LAMBDA_0" is 50.6mb which exceeds the maximum size limit of 50mb. (@aggre)

Deleting unused pages may fix the problem. `packages/web/src/pages/auth/[market]/AuthForm.tsx` and `packages/web/src/pages/author/useWindowDimensions.tsx` are not page, so you should remove this component from the `/pages` directory.

I often put page-specific components in the `/packages/web/src/components/_pages` directory.

You may also be able to solve it by changing `/settings/profile` to a shorter path like` /profile`.

>  Display name as name of creator page using dev-for-apps hook api (e.g. /author/0x00000C64586fC178E566aBadfD1119c03849520e) (@hhatto)

You can use `useGetAccount` in `packages/web/src/fixtures/dev-for-apps/hooks.ts`

>  Page logic invitation -> tokenization -> authentication (@aggre )

1. The user submits an application using the invitation form.
2. Dev Protocol team confirms the application and sends an invitation to the user. Simultaneously, the user's application is registered in the contract to prepare for user authentication.
3. The user accesses `/market/0x34A7AdC94C4D41C3e3469F98033B372cB2fAf318` to register authentication data and metadata (such as description and URL).
4. Use the `usePostSignGitHubMarketAsset` hook to get the Khaos public signature.
5. Use the `useCreateAndAuthenticate` hook to the Creator Token's creation and authenticate using the public signature. This flow requires an Ethereum transaction and oraclize, so it takes time.
6. If the authentication is successful, you can get the Creator Token address.
7. Use the Creator Token address as the UID and use the dev-for-apps hook to register the metadata. (It doesn't have this hook yet! @hhatto Can you create it?)
8. Done 

>  Profile header of creator page (@aggre)

https://github.com/dev-protocol/stakes.social/blob/profile-header/packages/web/src/components/_pages/profile/ProfileHeader/index.tsx

Is this helpful? In some cases, this component is still available to your `/author/[authorAddress]` page.

>  Property icon per pool on creator page -> Is here a field for in strapi API? (@hhatto/ @aggre)

`useGetProperty` in `packages/web/src/fixtures/dev-for-apps/hooks.ts`, and the field is `avatar`

>  Add creator description in About section from strapi API (@hhatto)

Is `Account.biography` missing?

**Comment by hhatto** [comment]
> 7. Use the Creator Token address as the UID and use the dev-for-apps hook to register the metadata. (It doesn't have this hook yet! @hhatto Can you create it?)

OK 👌 
I'll add it today.

**Comment by hhatto** [comment]
@Cold-A-Muse @aggre 

I impl `useCreateProperty` and `useUpdateProperty` hooks.
https://github.com/dev-protocol/stakes.social/pull/763/files#diff-1af63bd2f72155fd33012f20792568c5c2939cce5d0c458dd7a573021b1fb95aR176
https://github.com/dev-protocol/stakes.social/pull/763/files#diff-1af63bd2f72155fd33012f20792568c5c2939cce5d0c458dd7a573021b1fb95aR226

enable to update Account.links(github, website), Property.links too.
https://github.com/dev-protocol/stakes.social/pull/763/files#diff-1af63bd2f72155fd33012f20792568c5c2939cce5d0c458dd7a573021b1fb95aR126-R141

And reference implementation of updating Account.links on profile edit page has also been added.
https://github.com/dev-protocol/stakes.social/pull/763/files#diff-54a75babb3cef476ef03278f4a6711d2ed412547f7aef4ddc8e04a8957413ae9

**Comment by Cold-A-Muse** [comment]
> @Cold-A-Muse @aggre
> 
> I impl `useCreateProperty` and `useUpdateProperty` hooks.
> https://github.com/dev-protocol/stakes.social/pull/763/files#diff-1af63bd2f72155fd33012f20792568c5c2939cce5d0c458dd7a573021b1fb95aR176
> https://github.com/dev-protocol/stakes.social/pull/763/files#diff-1af63bd2f72155fd33012f20792568c5c2939cce5d0c458dd7a573021b1fb95aR226
> 
> enable to update Account.links(github, website), Property.links too.
> https://github.com/dev-protocol/stakes.social/pull/763/files#diff-1af63bd2f72155fd33012f20792568c5c2939cce5d0c458dd7a573021b1fb95aR126-R141
> 
> And reference implementation of updating Account.links on profile edit page has also been added.
> https://github.com/dev-protocol/stakes.social/pull/763/files#diff-54a75babb3cef476ef03278f4a6711d2ed412547f7aef4ddc8e04a8957413ae9

Thanks @hhatto ! Question: Does an author have to be created in strapi before you can update an user?

**Comment by aggre** [comment]
@Cold-A-Muse "found" is a confusing name, sorry. That original meaning is "responded". That is, it indicates that the API response has been completed.

**Review by aggre — APPROVED** [review]
I tweaked the header, font families, etc. I'll merge this when it passes the test! (Anyone can merge this if I do not notice the test)

**Pull request merged**
