### PR TITLE
Add social links with assets

### PR DESCRIPTION
**Pull request by hhatto**
## Proposed Changes
Some consideration was not enough in #753 .
This problem only occurs in vyperlang vyper's Pool page.

## Implementation
* Fixed so that the error does not occur even if `links` attribute does not exist in `Property`

### CODE REVIEW

**Comment by Cold-A-Muse** [comment]
Right now when u click one of the buttons it will redirect the user to this url within the same tab. I'd sugges to add a __blank target to it so the social medial link will be opened in a new tab. Do you agree @hhatto  ?

**Comment by hhatto** [comment]
> Right now when u click one of the buttons it will redirect the user to this url within the same tab. I'd sugges to add a __blank target to it so the social medial link will be opened in a new tab. Do you agree @hhatto ?

@Cold-A-Muse 
That's nice. 
add `target="_blank"` and `rel="noopener noreferrer"` attributes with `<a>` tag.
Can I include in this PR?

**Comment by Cold-A-Muse** [comment]
> > Right now when u click one of the buttons it will redirect the user to this url within the same tab. I'd sugges to add a __blank target to it so the social medial link will be opened in a new tab. Do you agree @hhatto ?
> 
> @Cold-A-Muse
> That's nice.
> add `target="_blank"` and `rel="noopener noreferrer"` attributes with `<a>` tag.
> Can I include in this PR?

Yes if you add this the PR can be merged imo :+1:

**Comment by hhatto** [comment]
> > > Right now when u click one of the buttons it will redirect the user to this url within the same tab. I'd sugges to add a __blank target to it so the social medial link will be opened in a new tab. Do you agree @hhatto ?
> > 
> > 
> > @Cold-A-Muse
> > That's nice.
> > add `target="_blank"` and `rel="noopener noreferrer"` attributes with `<a>` tag.
> > Can I include in this PR?
> 
> Yes if you add this the PR can be merged imo 👍

fix in 92132797414026edd5255540b8c1c0ecf8b34b89

**Comment by aggre** [comment]
Good! I think can be merge this!

**Pull request merged**
