### PR TITLE
adds upload to ipfs using nft.storage hook

### LINKED ISSUE #1954: React Hook for uploading image to IPFS via nft.storage
### What would you like to share?

[The UI](https://github.com/dev-protocol/stakes.social/issues/1953), when "Attach with IPFS" is clicked, needs a React Hooks function that pushes the image to IPFS and returns its hash value.

IPFS can't persist a file without pinning it, so use nft.storage to delegate file persistence to the service.

Doc at nft.storage: https://nftstorage.github.io/nft.storage/client/

## Expected interface
This Hooks function returns a function that calls `useCallback`.
Similar existing Hook, useStake: https://github.com/dev-protocol/stakes.social/blob/1979957709ad7cdf8b16df9326ebdc17142480c1/packages/web/src/fixtures/dev-kit/hooks.ts#L332-L359

- The input value of the returned function: File blob
- The return value of the returned function: IPFS address (like: `ipfs://eyxcd...`)

**_Of course, it is completely under the control of a developer._**

### Additional information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by stuartwk**
## Proposed Changes
Closes #1954 

## Implementation
Adds `src/fixtures/ipfs` with hook for uploading image using nft.storage

### CODE REVIEW

**Comment by aggre** [comment]
This implementation looks perfect except for the environment variable dependent parts!

**Comment by aggre** [comment]
Oops, I noticed from the nft.storage docs, `NFTStorage.store` function stores all (unnecessary) metadata such as name and description, not only image. And I found `NFTStorage.storeBlob` function that seems more appropriate, and the sample is here: https://github.com/nftstorage/nft.storage/blob/main/packages/client/examples/browser/storeBlob.html

Shouldn't the implementation be changed to `NFTStorage.storeBlob`?

**Review by aggre — APPROVED** [review]
If the test is successful, it's perfect!

**Comment by hhatto** [comment]
is this impl still in progress? @stuartwk @aggre

**Comment by hhatto** [comment]
resolve conflict.
I will try to integrate this pr with #1962.

**Comment by hhatto** [comment]
ummm, test is fail...
check this one.

**Comment by hhatto** [comment]
It has been merged over to #1983 🚀 
This issue is closed.

**Pull request closed without merging**
